//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DictionaryOposites
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        public string Name { get; set; }
        public int Cislo { get; set; }
        public string Popis { get; set; }
        public int Id { get; set; }
    }
}
